[package]
name = "rls-vfs"
version = "0.1.0"
authors = ["Nick Cameron <ncameron@mozilla.com>"]

[dependencies]
rls-analysis = { git = "https://github.com/nrc/rls-analysis" }
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8"
